name: CI Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  security:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # 🔍 Scan dépendances
      - name: Run Trivy FS scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: fs
          scan-ref: .
          severity: HIGH,CRITICAL

      # 🐳 Build image Docker
      - name: Build Docker image
        run: docker build -t devsecops-app ./app

      # 🔍 Scan image Docker
      - name: Run Trivy image scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: devsecops-app
          severity: HIGH,CRITICAL

      # 🔐 Policy Kubernetes
      - name: Run Conftest
        run: |
          curl -L -o conftest.tar.gz https://github.com/open-policy-agent/conftest/releases/latest/download/conftest_Linux_x86_64.tar.gz
          tar xzf conftest.tar.gz
          ./conftest test k8s/deployment.yaml
